{
  config,
  pkgs,
  lib,
  ...
}:
# note: surprisingly, a LOT of stuff in searching nixos packages has support for aarch64-darwin, which is crazy to think of! like imagine arm64 / mac+linux being first class citizens in arch! nix is crazy
# i will only use brew if the build fails / im lazy or it doesnt exist
{
  homebrew = {
    enable = true;
    onActivation = {
      autoUpdate = false;
      cleanup = "zap";
      upgrade = true;
    };

    taps = [
      "blacktop/tap"
      "bloznelis/tap"
      # "charmbracelet/tap"
      "esolitos/ipa"
      # "felixkratz/formulae"
      # "koekeishiya/formulae"
      "lhvy/tap"
      # "nasa-sw-vnv/core"
      # "oven-sh/bun"
      # "pkgxdev/made"
      "tw93/tap"
    ];

    brews = [
      # "atomicparsley"
      # "ripgrep"
      # "btop"
      "bzip2"
      # "neovim"
      "cabextract"
      # "cava"
      # "cbonsai"
      # "cdrtools"
      # "chafa"
      # "cmatrix"
      "cocoapods"
      # "codex"
      # "cowsay"
      "dbus"
      "dfu-util"
      # "eza"
      # "fastfetch"
      # "fcrackzip"
      "fd"
      "file-formula"
      # "fortune"
      # "fzf"
      "gawk"
      # "gh"
      # "ghostscript"
      # "gifsicle"
      # "git"
      # "git-lfs"
      # "gitui"
      # "glyph"
      "gnu-sed"
      "gnu-tar"
      # "gotop"
      # "graphviz"
      # "grep"
      # "helix"
      # "hugo"
      # "hyperfine"
      # "icu4c@76"
      # "imagemagick"
      # "iperf3"
      # "irssi"
      # "jadx"
      # "jq"
      # "ldid"
      # "libimobiledevice"
      # "libirecovery"
      # "luarocks"
      # "lynx"
      "mas"
      "media-control"
      "montage"
      # "mpd"
      # "mpdscribble"
      # "ncdu"
      # "ncspot"
      # "neofetch"
      # "neovide"
      # "node"
      # "node@24"
      "openldap"
      "p7zip"
      # "pfetch"
      "picocom"
      # "pidof"
      "powerlevel10k"
      # "qpdf"
      # "rclone"
      "rename"
      # "ruff"
      # "rustup"
      # "sl"
      "smartmontools"
      # "solargraph"
      # "speedtest-cli"
      "spicetify-cli"
      # "stow"
      "switchaudio-osx"
      "tailscale"
      # "tcl-tk"
      # "tokei"
      # "tree"
      "usbutils"
      # "uv"
      "watch"
      # "wget"
      "wimlib"
      "yazi"
      # "zellij"
      # "zoxide"
      "zsh-autosuggestions"
      "zsh-syntax-highlighting"
      "blacktop/tap/ipsw"
      # "bloznelis/tap/typioca"
      # "charmbracelet/tap/freeze"
      # "esolitos/ipa/sshpass"
      # "felixkratz/formulae/sketchybar"
      # "koekeishiya/formulae/skhd"
      # "lhvy/tap/pipes-rs"
      # "nasa-sw-vnv/core/apron"
      # "oven-sh/bun/bun"
      # "pkgxdev/made/pkgx"
      "tw93/tap/mole"
    ];

    casks = [
      # "aerospace"
      "android-commandlinetools"
      "background-music"
      "battery"
      "blackhole-2ch"
      "charles"
      # "chatgpt-atlas"
      # "chromedriver"
      "clion"
      "discord"
      "disk-inventory-x"
      # "dotnet-sdk"
      # "expo-orbit"
      "figma"
      # "firefox"
      # "flutter"
      "font-jetbrains-mono-nerd-font"
      "font-sf-mono"
      "font-sf-pro"
      # "gcloud-cli"
      "ghostty"
      "helium-browser"
      # "huggingchat"
      # "ipatool"
      # "kicad"
      # "kitty"
      "microsoft-auto-update"
      "microsoft-outlook"
      "microsoft-teams"
      "microsoft-word"
      "mitmproxy"
      "obs"
      "obsidian" # not packaged for aarch64-darwin
      "omnidisksweeper"
      "orbstack"
      "parsec"
      "postman"
      "prismlauncher"
      "proxyman"
      "qbittorrent"
      "raycast"
      "sf-symbols"
      "signal"
      "slack"
      "spotify" # spicetify nix sucks
      "telegram"
      "the-unarchiver"
      # "transmission"
      # "unnaturalscrollwheels"
      "visual-studio-code"
      "vlc"
      "webstorm"
      "whatsapp"
      # "wireshark"
      "zed"
      "blacktop/tap/ida-mcp"
      "zoom"
    ];

    masApps = {
      # Add App Store apps here if needed
      # "App Name" = app_id;
    };
  };
}
