# windowrule = float, file_progress
# windowrule = float, confirm
# windowrule = float, dialog
# windowrule = float, download
# windowrule = float, notification
# windowrule = float, error
# windowrule = float, splash
# windowrule = float, confirmreset
# windowrule = float, title:Open File
# windowrule = float, title:branchdialog
# windowrule = float,viewnior
# windowrule = float, pavucontrol-qt
# windowrule = float, pavucontrol
# windowrule = float, file-roller
# windowrule = fullscreen, wlogout
# windowrule = float, title:wlogout
# windowrule = fullscreen, title:wlogout
# windowrule = idleinhibit stayfocused, mpv
# windowrulev2 = float, title:^(Media viewer)$

# Picture in picture windows
windowrule {
  name = windowrule-1
  float = on
  pin = on
  match:title = ^(Picture-in-Picture)$
}

windowrule {
  name = windowrule-2
  float = on
  pin = on
  match:class = ^(vesktop)$
  match:title = ^(Discord Popout)$
}

windowrule {
  name = windowrule-3
  float = on
  match:class = ^(steam)$
  match:title = ^(Friends List)$
}
