[General]
configversion=2

[fft]
averaging=50
fft_rate=25
fft_size=8192
pandapter_min_db=-90
waterfall_min_db=-90

[input]
bandwidth=1536000
device="soapy=0,driver=soapyMiri"
frequency=100000000
sample_rate=2048000

[receiver]
demod=0
